### ISSUE TITLE
Volume path parsing seems broken

### ISSUE THREAD

**Issue by pkarakal** [containers/podman-compose#222] opened 2020-07-23 20:37 UTC
In the docker-compose.yml, under the volumes I have the following 

```
volumes:
      - ./environment/configuration/app.json:/usr/share/nginx/html/assets/config/app.json
```

When running `podman-compose up` I see that the path of the volume gets tangled up and instead of getting `$(pwd)/environment/configuration/app.json`, I see `$(pwd)/./environment/configuration/app.json` and this way the container cannot cannot start. 

### Environment
OS/Distro: Fedora 32
Podman version: 
```
podman --version
podman version 2.0.2
```
podman-compose version:
```
Name         : podman-compose
Version      : 0.1.5
```

Maybe it's something worth taking a look into. 
When running `docker-compose up` it seems to start the container just fine.

**Comment by elmariachi111** [comment] 2020-07-27 18:46
what happens when you  add a `:Z` at the end?

```
volumes:
      - ./environment/configuration/app.json:/usr/share/nginx/html/assets/config/app.json:Z
```

?

**Comment by pkarakal** [comment] 2020-07-30 10:38
> what happens when you add a `:Z` at the end?
> 
> ```
> volumes:
>       - ./environment/configuration/app.json:/usr/share/nginx/html/assets/config/app.json:Z
> ```
> 
> ?

@elmariachi111 I don't see any change. This still does the same thing when parsing the volume path unfortunately.

**Comment by pkarakal** [comment] 2020-08-06 00:09
replacing the `./` with `${PWD}/` seems to eliminate the weird parsing. 

I also added a bind-propagation parameter `./environment/configuration/app.json:/usr/share/nginx/html/assets/config/app.json:rshared`  and it seems to be fine

**Comment by JonasKs** [comment] 2020-08-18 16:58
Please don't close the issue because a workaround has been found, when the issue is still valid. 

I've encountered the same now, and the fix was indeed replacing `./` with `${PWD}`.

**Comment by pkarakal** [comment] 2020-08-18 17:53
The issue on the code seems to get fixed when using `os.path.realpath` when parsing the volumes. (This is a TODO here https://github.com/containers/podman-compose/blob/devel/podman_compose.py#L90) .

**Comment by muayyad-alsadi** [comment] 2021-12-10 00:13
would you please confirm that this bug is still there in latest code?

**Comment by pkarakal** [comment] 2021-12-10 17:43
> would you please confirm that this bug is still there in latest code?

yeap. The bug still persists. tried it with the latest master branch.

**Comment by muayyad-alsadi** [comment] 2021-12-10 20:27
the following are equivalent and ./ or multiple /// are valid

```
$(pwd)/environment/configuration/app.json
$(pwd)/./environment/configuration/app.json
$(pwd)/////environment/configuration/app.json
```

despite that I'll fix it

**Closed by muayyad-alsadi** 2021-12-10 20:27 UTC
