### ISSUE TITLE
Create non-existing bind volumes

### ISSUE THREAD

**Issue by maweki** [containers/podman-compose#185] opened 2020-05-25 09:28 UTC
I am not sure whether `docker` or `docker-compose` does this and conversely I don't know whether the issue lies with `podman` or `podman-compose`:

For postgres containers we often have a setup like this:

```
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - "./pg-data:/var/lib/postgresql/data"
```

in docker the folder `pg-data` is created automatically, if it doesn't exist. Via podman-compose I get

```
Error: error checking path "/tmp/foo/./pg-data": stat /tmp/foo/./pg-data: no such file or directory
125
```

**Comment by manics** [comment] 2020-05-25 09:48
It's an issue with podman, see https://github.com/containers/podman-compose/issues/175

**Comment by akirabaruah** [comment] 2020-07-06 01:18
It seems like this feature is intentionally left out of libpod / podman - see these comments by @rhatdan:
- https://github.com/containers/libpod/issues/4891#issuecomment-575778042
- https://github.com/containers/libpod/issues/6234#issuecomment-628842681

I ran into this issue myself and worked around it by creating the required directories using `mkdir` on the host before running `podman-compose`.

In that case, should we close this issue as working as intended?

**Comment by maweki** [comment] 2020-07-06 07:40
This is intentionally breaking drop-in-replaceability of podman/podman-compose with docker/docker-compose. Maybe we can hide it behind a command line switch.

I often have database containers with the data directory of the database mounted into the filesystem. Resetting after I changed something in the build of the container is:

`podman-compose down && sudo rm -rf ./data && mkdir data && podman-compose build && podman-compose up` instead of just `docker-compose down && sudo rm -rf ./data && docker-compose build && docker-compose up` and then I often forget to create the data directory before restarting the container.

In the ideal world, podman-compose has a compatibility mode with docker-compose where it tries to behave as a drop-in replacement and I can alias `docker-compose` to `podman-compose -C` or something.

We are thinking about enabling podman in the future for our students in the pc laboratory and I stumble over this quite often. I am 100% sure that most students would get this wrong even after explaining it a dozen times.

**Comment by lcarva** [comment] 2020-07-06 17:55
I'm happy to add some sort of compatibility flag if that's preferable. Any objections?

**Comment by lcarva** [comment] 2020-10-13 21:12
Updated the PR to include the compatibility mode.

**Comment by muayyad-alsadi** [comment] 2020-10-13 21:59
> I'm happy to add some sort of compatibility flag if that's preferable. Any objections?

the default behavior should be just like docker-compose.
maybe not deleting volumes resulted from legacy code that predates the volume support in podman (maybe we did it when podman had bind volumes only)

but if you think there is a value of having an extra functionality it should not be default.

Not deleting the volumes is something useful I would love a flag to keep it.
But we need to double check to see if docker-compose have a flag to keep the volumes.

**Comment by lcarva** [comment] 2020-10-14 15:20
> > I'm happy to add some sort of compatibility flag if that's preferable. Any objections?
> 
> the default behavior should be just like docker-compose.
> maybe not deleting volumes resulted from legacy code that predates the volume support in podman (maybe we did it when podman had bind volumes only)
> 
> but if you think there is a value of having an extra functionality it should not be default.
> 
> Not deleting the volumes is something useful I would love a flag to keep it.
> But we need to double check to see if docker-compose have a flag to keep the volumes.

@muayyad-alsadi, this issue and the linked PR #194 are about creating bind volumes, not deleting named volumes (that's my other PR https://github.com/containers/podman-compose/pull/214 :smile: ). `docker-compose` will create directories for bind volumes if they don't exist. More specifically, `docker` creates these. As previously [mentioned](https://github.com/containers/podman-compose/issues/185#issuecomment-653969004), there was a decision to not implement this behavior in podman which breaks compatibility between podman-compose and docker-compose.

**Comment by lcarva** [comment] 2021-11-23 13:12
@stellarpower, that wouldn't help with keeping compatibility between docker-compose and podman-compose. I like your idea though. I think a better place to implement such feature would be in podman itself. Maybe file an feature request there?

**Comment by muayyad-alsadi** [comment] 2021-12-10 20:47
@lcarva @stellarpower  please test

**Closed** 2021-12-10 20:46 UTC
